# Generated by Django 5.0.3 on 2024-06-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0007_pista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pista',
            name='largo',
            field=models.CharField(max_length=128),
        ),
    ]
