# Generated by Django 5.0.3 on 2024-06-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0008_alter_pista_largo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='directors',
            field=models.ManyToManyField(blank=True, to='pilotos.director'),
        ),
        migrations.AddField(
            model_name='user',
            name='pistas',
            field=models.ManyToManyField(blank=True, to='pilotos.pista'),
        ),
    ]
